name: CD staging

on:
  push:
    branches:
      - develop
    tags-ignore:
      - '*'

jobs:
  cd-prod:
    if: github.event_name == 'push' && github.ref == 'refs/heads/develop'
    needs: [ci]
    runs-on: ubuntu-latest
    container:
      image: stayallive/php:7.3
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Run composer install
        uses: docker://stayallive/composer-install
      - name: Enable PHP extensions
        run: docker-php-ext-enable zip
      - name: Deploy to staging
        run: vendor/bin/vapor deploy staging
        env:
          VAPOR_API_TOKEN: ${{ secrets.VAPOR_API_TOKEN }}
      - name: Notify Sentry
        uses: docker://stayallive/sentry:release
        env:
          PLUGIN_DEPLOY: 'staging'
          PLUGIN_SENTRY_URL: 'https://observ.app/'
          PLUGIN_SENTRY_ORG: 'irongate'
          PLUGIN_SENTRY_PROJECT: 'pkgtrends'
          PLUGIN_SENTRY_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
